package db

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
)

// RequestConfig holds per-monitor check customization. TimeoutSeconds and RetryCount
// apply to every monitor type; the remaining fields are only read by the check type
// they belong to (HTTP request options, DNS lookup options).
type RequestConfig struct {
	Method              string            `json:"method,omitempty"`
	Headers             map[string]string `json:"headers,omitempty"`
	Body                string            `json:"body,omitempty"`
	TimeoutSeconds      int               `json:"timeoutSeconds,omitempty"`
	FollowRedirects     *bool             `json:"followRedirects,omitempty"`
	AcceptedStatusCodes string            `json:"acceptedStatusCodes,omitempty"`
	RetryCount          int               `json:"retryCount,omitempty"`

	// DNS-only options.
	DNSRecordType string `json:"dnsRecordType,omitempty"` // A, AAAA, MX, NS, TXT (default A)
	DNSResolver   string `json:"dnsResolver,omitempty"`   // resolver to query, host or host:port (default system)
}

// IsEmpty returns true if all fields are at their zero/default values.
func (rc *RequestConfig) IsEmpty() bool {
	return rc.Method == "" && len(rc.Headers) == 0 && rc.Body == "" &&
		rc.TimeoutSeconds == 0 && rc.FollowRedirects == nil &&
		rc.AcceptedStatusCodes == "" && rc.RetryCount == 0 &&
		rc.DNSRecordType == "" && rc.DNSResolver == ""
}

// Check types a monitor can run against its target.
const (
	MonitorTypeHTTP = "http" // GET/POST an URL and inspect the status code
	MonitorTypeTCP  = "tcp"  // open a TCP connection to host:port
	MonitorTypePing = "ping" // ICMP echo request to a host
	MonitorTypeDNS  = "dns"  // resolve a name, optionally against a specific resolver
)

// NormalizeMonitorType fills in the default for monitors stored before check types
// existed, which read back with an empty type.
func NormalizeMonitorType(t string) string {
	if t == "" {
		return MonitorTypeHTTP
	}
	return t
}

// IsValidMonitorType reports whether t is a check type Warden knows how to run.
func IsValidMonitorType(t string) bool {
	switch t {
	case MonitorTypeHTTP, MonitorTypeTCP, MonitorTypePing, MonitorTypeDNS:
		return true
	}
	return false
}

// ErrMonitorNotFound is returned when a monitor is not found
var ErrMonitorNotFound = errors.New("monitor not found")

type Monitor struct {
	ID string `json:"id"`
	// Type selects the check performed against URL: http, tcp, ping or dns.
	// Empty means http, so monitors created before check types existed keep working.
	Type                    string         `json:"type"`
	GroupID                 string         `json:"groupId"`
	Name                    string         `json:"name"`
	URL                     string         `json:"url"`
	Active                  bool           `json:"active"`
	Interval                int            `json:"interval"` // Seconds
	CreatedAt               time.Time      `json:"createdAt"`
	ConfirmationThreshold   *int           `json:"confirmationThreshold,omitempty"`
	NotificationCooldownMin *int           `json:"notificationCooldownMinutes,omitempty"`
	LatencyThreshold        *int           `json:"latencyThreshold,omitempty"`
	RequestConfig           *RequestConfig `json:"requestConfig,omitempty"`
}

type CheckResult struct {
	MonitorID  string    `json:"monitorId"`
	Status     string    `json:"status"`
	Latency    int64     `json:"latency"`
	Timestamp  time.Time `json:"timestamp"`
	StatusCode int       `json:"statusCode"`
}

type MonitorEvent struct {
	ID        int       `json:"id"`
	MonitorID string    `json:"monitorId"`
	Type      string    `json:"type"`
	Message   string    `json:"message"`
	Timestamp time.Time `json:"timestamp"`

	// Enriched diagnostic detail captured from the check that triggered this event.
	// Populated only for events generated by a real check result (down/degraded/recovered);
	// flapping/stabilized/ssl_expiring events leave these nil.
	StatusCode      *int    `json:"statusCode,omitempty"`
	Latency         *int64  `json:"latency,omitempty"`
	ErrorMessage    *string `json:"errorMessage,omitempty"`
	ResponseBody    *string `json:"responseBody,omitempty"`
	ResponseHeaders *string `json:"responseHeaders,omitempty"`
}

// EventDetails carries optional enriched data captured from the underlying check.
// Pass nil to CreateEvent when the event isn't tied to a specific HTTP response
// (e.g. flapping detection, stabilization).
type EventDetails struct {
	StatusCode      int
	Latency         int64
	ErrorMessage    string
	ResponseBody    string
	ResponseHeaders string
}

type MonitorOutage struct {
	ID          int64      `json:"id"`
	MonitorID   string     `json:"monitorId"`
	Type        string     `json:"type"`
	Summary     string     `json:"summary"`
	StartTime   time.Time  `json:"startTime"`
	EndTime     *time.Time `json:"endTime"`
	MonitorName string     `json:"monitorName"` // Joined
	GroupName   string     `json:"groupName"`   // Joined
	GroupID     string     `json:"groupId"`     // Joined
}

type LatencyPoint struct {
	Timestamp time.Time `json:"timestamp"`
	Latency   int64     `json:"latency"`
	Failed    bool      `json:"failed"`
}

// Monitor CRUD

func (s *Store) CreateMonitor(m Monitor) error {
	if m.Interval < 1 {
		m.Interval = 60 // Default safety
	}
	var reqCfg sql.NullString
	if m.RequestConfig != nil && !m.RequestConfig.IsEmpty() {
		b, err := json.Marshal(m.RequestConfig)
		if err != nil {
			return fmt.Errorf("failed to marshal request_config: %w", err)
		}
		reqCfg = sql.NullString{String: string(b), Valid: true}
	}
	_, err := s.db.Exec(s.rebind("INSERT INTO monitors (id, type, group_id, name, url, active, interval_seconds, created_at, confirmation_threshold, notification_cooldown_minutes, latency_threshold, request_config) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"),
		m.ID, NormalizeMonitorType(m.Type), m.GroupID, m.Name, m.URL, m.Active, m.Interval, time.Now(), toNullInt64(m.ConfirmationThreshold), toNullInt64(m.NotificationCooldownMin), toNullInt64(m.LatencyThreshold), reqCfg)
	return err
}

func (s *Store) UpdateMonitor(id, monitorType, name, url string, interval int, confirmThreshold *int, cooldownMins *int, latencyThreshold *int, reqConfig *RequestConfig) error {
	if interval < 1 {
		interval = 60
	}
	var reqCfg sql.NullString
	if reqConfig != nil && !reqConfig.IsEmpty() {
		b, err := json.Marshal(reqConfig)
		if err != nil {
			return fmt.Errorf("failed to marshal request_config: %w", err)
		}
		reqCfg = sql.NullString{String: string(b), Valid: true}
	}
	// Don't modify active flag - it's managed separately via SetMonitorActive
	res, err := s.db.Exec(s.rebind("UPDATE monitors SET type = ?, name = ?, url = ?, interval_seconds = ?, confirmation_threshold = ?, notification_cooldown_minutes = ?, latency_threshold = ?, request_config = ? WHERE id = ?"),
		NormalizeMonitorType(monitorType), name, url, interval, toNullInt64(confirmThreshold), toNullInt64(cooldownMins), toNullInt64(latencyThreshold), reqCfg, id)
	if err != nil {
		return err
	}
	rows, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if rows == 0 {
		return fmt.Errorf("monitor not found")
	}
	return nil
}

func (s *Store) DeleteMonitor(id string) error {
	_, err := s.db.Exec(s.rebind("DELETE FROM monitors WHERE id = ?"), id)
	return err
}

func (s *Store) SetMonitorActive(id string, active bool) error {
	res, err := s.db.Exec(s.rebind("UPDATE monitors SET active = ? WHERE id = ?"), active, id)
	if err != nil {
		return fmt.Errorf("failed to update monitor active status: %w", err)
	}
	rows, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("failed to get rows affected: %w", err)
	}
	if rows == 0 {
		return ErrMonitorNotFound
	}
	return nil
}

// GetMonitors returns all monitors
func (s *Store) GetMonitors() ([]Monitor, error) {
	rows, err := s.db.Query("SELECT id, type, group_id, name, url, active, interval_seconds, created_at, confirmation_threshold, notification_cooldown_minutes, latency_threshold, request_config FROM monitors ORDER BY created_at ASC")
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var monitors []Monitor
	for rows.Next() {
		var m Monitor
		var confirmThreshold, cooldownMins, latencyThresh sql.NullInt64
		var reqCfgStr sql.NullString
		if err := rows.Scan(&m.ID, &m.Type, &m.GroupID, &m.Name, &m.URL, &m.Active, &m.Interval, &m.CreatedAt, &confirmThreshold, &cooldownMins, &latencyThresh, &reqCfgStr); err != nil {
			return nil, err
		}
		m.Type = NormalizeMonitorType(m.Type)
		if confirmThreshold.Valid {
			v := int(confirmThreshold.Int64)
			m.ConfirmationThreshold = &v
		}
		if cooldownMins.Valid {
			v := int(cooldownMins.Int64)
			m.NotificationCooldownMin = &v
		}
		if latencyThresh.Valid {
			v := int(latencyThresh.Int64)
			m.LatencyThreshold = &v
		}
		if reqCfgStr.Valid && reqCfgStr.String != "" {
			var rc RequestConfig
			if err := json.Unmarshal([]byte(reqCfgStr.String), &rc); err != nil {
				return nil, fmt.Errorf("failed to unmarshal request_config for monitor %s: %w", m.ID, err)
			}
			m.RequestConfig = &rc
		}
		monitors = append(monitors, m)
	}
	return monitors, nil
}

// Events & Checks

func (s *Store) CreateEvent(monitorID, eventType, message string) error {
	return s.CreateEventWithDetails(monitorID, eventType, message, nil)
}

// CreateEventWithDetails records a monitor event optionally enriched with diagnostic data
// (status code, latency, error message, response body excerpt, response headers).
// Pass nil for details when the event isn't tied to a concrete HTTP response.
func (s *Store) CreateEventWithDetails(monitorID, eventType, message string, d *EventDetails) error {
	var (
		statusCode sql.NullInt64
		latency    sql.NullInt64
		errMsg     sql.NullString
		body       sql.NullString
		headers    sql.NullString
	)
	if d != nil {
		if d.StatusCode > 0 {
			statusCode = sql.NullInt64{Int64: int64(d.StatusCode), Valid: true}
		}
		if d.Latency > 0 {
			latency = sql.NullInt64{Int64: d.Latency, Valid: true}
		}
		if d.ErrorMessage != "" {
			errMsg = sql.NullString{String: d.ErrorMessage, Valid: true}
		}
		if d.ResponseBody != "" {
			body = sql.NullString{String: d.ResponseBody, Valid: true}
		}
		if d.ResponseHeaders != "" {
			headers = sql.NullString{String: d.ResponseHeaders, Valid: true}
		}
	}
	_, err := s.db.Exec(s.rebind(
		`INSERT INTO monitor_events
			(monitor_id, type, message, status_code, latency, error_message, response_body, response_headers)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?)`),
		monitorID, eventType, message, statusCode, latency, errMsg, body, headers)
	return err
}

func (s *Store) CreateOutage(monitorID, eventType, summary string) error {
	_, err := s.db.Exec(s.rebind("INSERT INTO monitor_outages (monitor_id, type, summary) VALUES (?, ?, ?)"),
		monitorID, eventType, summary)
	return err
}

func (s *Store) CloseOutage(monitorID string) error {
	// Close any active outages for this monitor
	_, err := s.db.Exec(s.rebind("UPDATE monitor_outages SET end_time = CURRENT_TIMESTAMP WHERE monitor_id = ? AND end_time IS NULL"), monitorID)
	return err
}

// OutageFilter scopes outage lookups to a specific monitor and/or group. Both fields
// are optional; empty strings mean "no filter on this dimension". Used to power the
// IncidentsView filter row and MonitorPage's per-monitor rollup view.
type OutageFilter struct {
	MonitorID string
	GroupID   string
}

func (s *Store) GetActiveOutages() ([]MonitorOutage, error) {
	return s.GetActiveOutagesFiltered(OutageFilter{})
}

func (s *Store) GetActiveOutagesFiltered(f OutageFilter) ([]MonitorOutage, error) {
	query := `
		SELECT o.id, o.monitor_id, o.type, o.summary, o.start_time, m.name, g.name, g.id
		FROM monitor_outages o
		JOIN monitors m ON o.monitor_id = m.id
		JOIN groups g ON m.group_id = g.id
		WHERE o.end_time IS NULL`
	args := []interface{}{}
	if f.MonitorID != "" {
		query += ` AND o.monitor_id = ?`
		args = append(args, f.MonitorID)
	}
	if f.GroupID != "" {
		query += ` AND m.group_id = ?`
		args = append(args, f.GroupID)
	}
	query += ` ORDER BY o.start_time DESC`

	rows, err := s.db.Query(s.rebind(query), args...)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var outages []MonitorOutage
	for rows.Next() {
		var o MonitorOutage
		if err := rows.Scan(&o.ID, &o.MonitorID, &o.Type, &o.Summary, &o.StartTime, &o.MonitorName, &o.GroupName, &o.GroupID); err != nil {
			return nil, err
		}
		outages = append(outages, o)
	}
	return outages, nil
}

func (s *Store) GetResolvedOutages(since time.Time) ([]MonitorOutage, error) {
	return s.GetResolvedOutagesFiltered(since, OutageFilter{})
}

func (s *Store) GetResolvedOutagesFiltered(since time.Time, f OutageFilter) ([]MonitorOutage, error) {
	query := `
		SELECT o.id, o.monitor_id, o.type, o.summary, o.start_time, o.end_time, m.name, g.name, g.id
		FROM monitor_outages o
		JOIN monitors m ON o.monitor_id = m.id
		JOIN groups g ON m.group_id = g.id
		WHERE o.end_time IS NOT NULL AND o.end_time >= ?`
	args := []interface{}{since}
	if f.MonitorID != "" {
		query += ` AND o.monitor_id = ?`
		args = append(args, f.MonitorID)
	}
	if f.GroupID != "" {
		query += ` AND m.group_id = ?`
		args = append(args, f.GroupID)
	}
	query += ` ORDER BY o.end_time DESC`

	rows, err := s.db.Query(s.rebind(query), args...)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var outages []MonitorOutage
	for rows.Next() {
		var o MonitorOutage
		var endTime sql.NullTime
		if err := rows.Scan(&o.ID, &o.MonitorID, &o.Type, &o.Summary, &o.StartTime, &endTime, &o.MonitorName, &o.GroupName, &o.GroupID); err != nil {
			return nil, err
		}
		if endTime.Valid {
			o.EndTime = &endTime.Time
		}
		outages = append(outages, o)
	}
	return outages, nil
}

// GetOutageByID returns a single outage by its ID
func (s *Store) GetOutageByID(id int64) (*MonitorOutage, error) {
	query := `
		SELECT o.id, o.monitor_id, o.type, o.summary, o.start_time, o.end_time, m.name, g.name, g.id
		FROM monitor_outages o
		JOIN monitors m ON o.monitor_id = m.id
		JOIN groups g ON m.group_id = g.id
		WHERE o.id = ?
	`
	var o MonitorOutage
	var endTime sql.NullTime
	err := s.db.QueryRow(s.rebind(query), id).Scan(&o.ID, &o.MonitorID, &o.Type, &o.Summary, &o.StartTime, &endTime, &o.MonitorName, &o.GroupName, &o.GroupID)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	if endTime.Valid {
		o.EndTime = &endTime.Time
	}
	return &o, nil
}

func (s *Store) BatchInsertChecks(checks []CheckResult) error {
	if len(checks) == 0 {
		return nil
	}

	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()

	stmt, err := tx.Prepare(s.rebind("INSERT INTO monitor_checks (monitor_id, status, latency, timestamp, status_code) VALUES (?, ?, ?, ?, ?)"))
	if err != nil {
		return err
	}
	defer func() { _ = stmt.Close() }()

	for _, c := range checks {
		_, err := stmt.Exec(c.MonitorID, c.Status, c.Latency, c.Timestamp, c.StatusCode)
		if err != nil {
			return err
		}
	}

	return tx.Commit()
}

// GetMonitorChecks returns the last N checks for a monitor
func (s *Store) GetMonitorChecks(monitorID string, limit int) ([]CheckResult, error) {
	query := s.rebind(`SELECT monitor_id, status, latency, timestamp, COALESCE(status_code, 0) FROM monitor_checks
			  WHERE monitor_id = ? ORDER BY timestamp DESC LIMIT ?`)

	rows, err := s.db.Query(query, monitorID, limit)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var checks []CheckResult
	for rows.Next() {
		var c CheckResult
		if err := rows.Scan(&c.MonitorID, &c.Status, &c.Latency, &c.Timestamp, &c.StatusCode); err != nil {
			return nil, err
		}
		checks = append(checks, c)
	}
	return checks, nil
}

// PruneMonitorEvents drops monitor events past the retention window.
//
// Events were the one table retention never covered, so a setting the UI calls "data
// retention" left them growing forever, and since each failed check can carry a couple
// of kilobytes of captured response body they grow fastest of all. Outages live in their
// own table, so incident history outlives the events behind it.
func (s *Store) PruneMonitorEvents(days int) error {
	if days < 1 || days > 3650 {
		return fmt.Errorf("invalid retention days: must be between 1 and 3650")
	}

	var err error
	if s.IsPostgres() {
		_, err = s.db.Exec("DELETE FROM monitor_events WHERE timestamp < NOW() - MAKE_INTERVAL(days => $1)", days)
	} else {
		_, err = s.db.Exec("DELETE FROM monitor_events WHERE timestamp < datetime('now', '-' || ? || ' days')", days)
	}
	return err
}

func (s *Store) PruneMonitorChecks(days int) error {
	// SECURITY: Validate input to prevent any potential issues
	if days < 1 || days > 3650 { // Max 10 years
		return fmt.Errorf("invalid retention days: must be between 1 and 3650")
	}

	var err error
	if s.IsPostgres() {
		// PostgreSQL: Use parameterized INTERVAL with MAKE_INTERVAL function
		_, err = s.db.Exec("DELETE FROM monitor_checks WHERE timestamp < NOW() - MAKE_INTERVAL(days => $1)", days)
	} else {
		// SQLite: Use parameterized query
		_, err = s.db.Exec("DELETE FROM monitor_checks WHERE timestamp < datetime('now', '-' || ? || ' days')", days)
	}
	return err
}

func (s *Store) GetUptimeStats(monitorID string) (float64, float64, float64, error) {
	var query string
	if s.IsPostgres() {
		query = `
			SELECT
				COUNT(CASE WHEN timestamp > NOW() - INTERVAL '1 days' THEN 1 END) as total_24h,
				COUNT(CASE WHEN timestamp > NOW() - INTERVAL '1 days' AND status = 'up' THEN 1 END) as up_24h,
				COUNT(CASE WHEN timestamp > NOW() - INTERVAL '7 days' THEN 1 END) as total_7d,
				COUNT(CASE WHEN timestamp > NOW() - INTERVAL '7 days' AND status = 'up' THEN 1 END) as up_7d,
				COUNT(CASE WHEN timestamp > NOW() - INTERVAL '30 days' THEN 1 END) as total_30d,
				COUNT(CASE WHEN timestamp > NOW() - INTERVAL '30 days' AND status = 'up' THEN 1 END) as up_30d
			FROM monitor_checks
			WHERE monitor_id = $1
		`
	} else {
		query = `
			SELECT
				COUNT(CASE WHEN timestamp > datetime('now', '-1 days') THEN 1 END) as total_24h,
				COUNT(CASE WHEN timestamp > datetime('now', '-1 days') AND status = 'up' THEN 1 END) as up_24h,
				COUNT(CASE WHEN timestamp > datetime('now', '-7 days') THEN 1 END) as total_7d,
				COUNT(CASE WHEN timestamp > datetime('now', '-7 days') AND status = 'up' THEN 1 END) as up_7d,
				COUNT(CASE WHEN timestamp > datetime('now', '-30 days') THEN 1 END) as total_30d,
				COUNT(CASE WHEN timestamp > datetime('now', '-30 days') AND status = 'up' THEN 1 END) as up_30d
			FROM monitor_checks
			WHERE monitor_id = ?
		`
	}
	var t24, u24, t7, u7, t30, u30 int
	err := s.db.QueryRow(query, monitorID).Scan(&t24, &u24, &t7, &u7, &t30, &u30)
	if err != nil {
		return 0, 0, 0, err
	}

	calc := func(up, total int) float64 {
		if total == 0 {
			return 100.0 // Assume 100% if no data
		}
		return (float64(up) / float64(total)) * 100.0
	}

	return calc(u24, t24), calc(u7, t7), calc(u30, t30), nil
}

func (s *Store) GetMonitorEvents(monitorID string, limit int) ([]MonitorEvent, error) {
	query := s.rebind(`SELECT id, monitor_id, type, message, timestamp,
		       status_code, latency, error_message, response_body, response_headers
	      FROM monitor_events
	      WHERE monitor_id = ?
	      ORDER BY timestamp DESC
	      LIMIT ?`)
	rows, err := s.db.Query(query, monitorID, limit)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	return scanEnrichedEvents(rows)
}

// GetRecentEventsForMonitors is the batched form of GetMonitorEvents: the most recent
// perMonitor events for every id in one query, keyed by monitor id. The dashboard polls
// the whole board every few seconds, so a query per monitor per poll adds up.
func (s *Store) GetRecentEventsForMonitors(ids []string, perMonitor int) (map[string][]MonitorEvent, error) {
	if perMonitor < 1 {
		perMonitor = 10
	}
	if len(ids) == 0 {
		return map[string][]MonitorEvent{}, nil
	}

	placeholders := make([]string, len(ids))
	args := make([]interface{}, 0, len(ids)+1)
	for i, id := range ids {
		placeholders[i] = "?"
		args = append(args, id)
	}
	args = append(args, perMonitor)

	query := s.rebind(fmt.Sprintf(`
		SELECT id, monitor_id, type, message, timestamp,
		       status_code, latency, error_message, response_body, response_headers
		FROM (
			SELECT id, monitor_id, type, message, timestamp,
			       status_code, latency, error_message, response_body, response_headers,
			       ROW_NUMBER() OVER (PARTITION BY monitor_id ORDER BY timestamp DESC, id DESC) AS rn
			FROM monitor_events
			WHERE monitor_id IN (%s)
		) ranked
		WHERE rn <= ?
		ORDER BY monitor_id, timestamp DESC, id DESC`, strings.Join(placeholders, ", ")))

	rows, err := s.db.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	events, err := scanEnrichedEvents(rows)
	if err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	out := make(map[string][]MonitorEvent, len(ids))
	for _, e := range events {
		out[e.MonitorID] = append(out[e.MonitorID], e)
	}
	return out, nil
}

// GetMonitorEventsBetween returns enriched events for a monitor between two timestamps (inclusive
// of start, exclusive of end), most recent first. Used to power the per-monitor day drill-down
// from the daily digest.
func (s *Store) GetMonitorEventsBetween(monitorID string, start, end time.Time, limit int) ([]MonitorEvent, error) {
	if limit <= 0 {
		limit = 500
	}
	query := s.rebind(`SELECT id, monitor_id, type, message, timestamp,
		       status_code, latency, error_message, response_body, response_headers
	      FROM monitor_events
	      WHERE monitor_id = ? AND timestamp >= ? AND timestamp < ?
	      ORDER BY timestamp DESC
	      LIMIT ?`)
	rows, err := s.db.Query(query, monitorID, start, end, limit)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	return scanEnrichedEvents(rows)
}

// GetEventsBetween returns all enriched monitor events in the time window, joined with monitor
// and group names. Used to reconstruct a daily digest for an arbitrary date.
func (s *Store) GetEventsBetween(start, end time.Time) ([]MonitorEventWithMonitor, error) {
	query := s.rebind(`SELECT e.id, e.monitor_id, e.type, e.message, e.timestamp,
		       e.status_code, e.latency, e.error_message, e.response_body, e.response_headers,
		       m.name, m.url, g.id, g.name
	      FROM monitor_events e
	      JOIN monitors m ON e.monitor_id = m.id
	      JOIN groups g ON m.group_id = g.id
	      WHERE e.timestamp >= ? AND e.timestamp < ?
	      ORDER BY e.timestamp ASC`)
	rows, err := s.db.Query(query, start, end)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var out []MonitorEventWithMonitor
	for rows.Next() {
		var e MonitorEventWithMonitor
		var statusCode, latency sql.NullInt64
		var errMsg, body, headers sql.NullString
		if err := rows.Scan(&e.ID, &e.MonitorID, &e.Type, &e.Message, &e.Timestamp,
			&statusCode, &latency, &errMsg, &body, &headers,
			&e.MonitorName, &e.MonitorURL, &e.GroupID, &e.GroupName); err != nil {
			return nil, err
		}
		if statusCode.Valid {
			v := int(statusCode.Int64)
			e.StatusCode = &v
		}
		if latency.Valid {
			v := latency.Int64
			e.Latency = &v
		}
		if errMsg.Valid {
			v := errMsg.String
			e.ErrorMessage = &v
		}
		if body.Valid {
			v := body.String
			e.ResponseBody = &v
		}
		if headers.Valid {
			v := headers.String
			e.ResponseHeaders = &v
		}
		out = append(out, e)
	}
	return out, nil
}

// MonitorEventWithMonitor is an enriched event joined with its monitor/group metadata,
// for the global daily digest reconstruction.
type MonitorEventWithMonitor struct {
	MonitorEvent
	MonitorName string `json:"monitorName"`
	MonitorURL  string `json:"monitorUrl"`
	GroupID     string `json:"groupId"`
	GroupName   string `json:"groupName"`
}

func scanEnrichedEvents(rows *sql.Rows) ([]MonitorEvent, error) {
	var events []MonitorEvent
	for rows.Next() {
		var e MonitorEvent
		var statusCode, latency sql.NullInt64
		var errMsg, body, headers sql.NullString
		if err := rows.Scan(&e.ID, &e.MonitorID, &e.Type, &e.Message, &e.Timestamp,
			&statusCode, &latency, &errMsg, &body, &headers); err != nil {
			return nil, err
		}
		if statusCode.Valid {
			v := int(statusCode.Int64)
			e.StatusCode = &v
		}
		if latency.Valid {
			v := latency.Int64
			e.Latency = &v
		}
		if errMsg.Valid {
			v := errMsg.String
			e.ErrorMessage = &v
		}
		if body.Valid {
			v := body.String
			e.ResponseBody = &v
		}
		if headers.Valid {
			v := headers.String
			e.ResponseHeaders = &v
		}
		events = append(events, e)
	}
	return events, nil
}

// SSLWarningEvent represents an SSL certificate expiry warning event
type SSLWarningEvent struct {
	ID          int       `json:"id"`
	MonitorID   string    `json:"monitorId"`
	MonitorName string    `json:"monitorName"`
	GroupName   string    `json:"groupName"`
	GroupID     string    `json:"groupId"`
	Message     string    `json:"message"`
	Timestamp   time.Time `json:"timestamp"`
}

// GetActiveSSLWarnings returns the most recent ssl_expiring event per monitor from the last 7 days
func (s *Store) GetActiveSSLWarnings() ([]SSLWarningEvent, error) {
	var query string
	if s.IsPostgres() {
		query = `
			SELECT e.id, e.monitor_id, m.name, g.name, g.id, e.message, e.timestamp
			FROM monitor_events e
			JOIN monitors m ON e.monitor_id = m.id
			JOIN groups g ON m.group_id = g.id
			WHERE e.type = 'ssl_expiring'
			AND e.timestamp >= NOW() - INTERVAL '7 days'
			AND e.id = (
				SELECT MAX(e2.id) FROM monitor_events e2
				WHERE e2.monitor_id = e.monitor_id
				AND e2.type = 'ssl_expiring'
				AND e2.timestamp >= NOW() - INTERVAL '7 days'
			)
			ORDER BY e.timestamp DESC
		`
	} else {
		query = `
			SELECT e.id, e.monitor_id, m.name, g.name, g.id, e.message, e.timestamp
			FROM monitor_events e
			JOIN monitors m ON e.monitor_id = m.id
			JOIN groups g ON m.group_id = g.id
			WHERE e.type = 'ssl_expiring'
			AND e.timestamp >= datetime('now', '-7 days')
			AND e.id = (
				SELECT MAX(e2.id) FROM monitor_events e2
				WHERE e2.monitor_id = e.monitor_id
				AND e2.type = 'ssl_expiring'
				AND e2.timestamp >= datetime('now', '-7 days')
			)
			ORDER BY e.timestamp DESC
		`
	}
	rows, err := s.db.Query(query)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var warnings []SSLWarningEvent
	for rows.Next() {
		var w SSLWarningEvent
		if err := rows.Scan(&w.ID, &w.MonitorID, &w.MonitorName, &w.GroupName, &w.GroupID, &w.Message, &w.Timestamp); err != nil {
			return nil, err
		}
		warnings = append(warnings, w)
	}
	return warnings, nil
}

// DailyUptimeStat holds uptime stats for a single day.
type DailyUptimeStat struct {
	Date          string  `json:"date"`
	Total         int     `json:"totalChecks"`
	Up            int     `json:"-"`
	UptimePercent float64 `json:"uptimePercent"`
}

// GetDailyUptimeStats returns per-day uptime percentages for the last N days.
func (s *Store) GetDailyUptimeStats(monitorID string, days int) ([]DailyUptimeStat, error) {
	if days < 1 || days > 365 {
		return nil, fmt.Errorf("invalid days: must be between 1 and 365")
	}

	var query string
	if s.IsPostgres() {
		query = `
			SELECT
				TO_CHAR(timestamp, 'YYYY-MM-DD') as day,
				COUNT(*) as total,
				SUM(CASE WHEN status = 'up' THEN 1 ELSE 0 END) as up_count
			FROM monitor_checks
			WHERE monitor_id = $1
			AND timestamp >= NOW() - MAKE_INTERVAL(days => $2)
			GROUP BY day
			ORDER BY day ASC
		`
	} else {
		query = `
			SELECT
				DATE(timestamp) as day,
				COUNT(*) as total,
				SUM(CASE WHEN status = 'up' THEN 1 ELSE 0 END) as up_count
			FROM monitor_checks
			WHERE monitor_id = ?
			AND timestamp >= datetime('now', '-' || ? || ' days')
			GROUP BY day
			ORDER BY day ASC
		`
	}

	rows, err := s.db.Query(s.rebind(query), monitorID, days)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	// Collect results from DB into a map for quick lookup
	dayMap := make(map[string]DailyUptimeStat)
	for rows.Next() {
		var stat DailyUptimeStat
		if err := rows.Scan(&stat.Date, &stat.Total, &stat.Up); err != nil {
			return nil, err
		}
		if stat.Total > 0 {
			stat.UptimePercent = (float64(stat.Up) / float64(stat.Total)) * 100.0
		}
		dayMap[stat.Date] = stat
	}

	// Build a complete slice with all days (fill gaps with no-data entries)
	now := time.Now().UTC()
	result := make([]DailyUptimeStat, days)
	for i := 0; i < days; i++ {
		d := now.AddDate(0, 0, -(days - 1 - i))
		dateStr := d.Format("2006-01-02")
		if stat, ok := dayMap[dateStr]; ok {
			result[i] = stat
		} else {
			result[i] = DailyUptimeStat{Date: dateStr, Total: 0, UptimePercent: -1} // -1 = no data
		}
	}

	return result, nil
}

// GetDailyUptimeStatsForMonitors returns per-day uptime for each monitor, read from the
// precomputed rollup table in one query. The public status page calls this on every load,
// so it reads the rollup instead of aggregating raw checks. Each id gets a filled slice,
// one entry per day oldest to newest; a day with no rollup row (no checks that day) is
// marked -1. Today's row is refreshed by the rollup worker, so it can trail by that
// worker's interval.
func (s *Store) GetDailyUptimeStatsForMonitors(ids []string, days int) (map[string][]DailyUptimeStat, error) {
	if days < 1 || days > 365 {
		return nil, fmt.Errorf("invalid days: must be between 1 and 365")
	}
	if len(ids) == 0 {
		return map[string][]DailyUptimeStat{}, nil
	}

	now := time.Now().UTC()
	oldest := now.AddDate(0, 0, -(days - 1)).Format("2006-01-02")

	placeholders := make([]string, len(ids))
	args := make([]interface{}, 0, len(ids)+1)
	for i, id := range ids {
		placeholders[i] = "?"
		args = append(args, id)
	}
	args = append(args, oldest)

	// day is 'YYYY-MM-DD', so a lexical >= is a date range.
	query := fmt.Sprintf(`SELECT monitor_id, day, total, up_count FROM monitor_uptime_daily
		WHERE monitor_id IN (%s) AND day >= ?`, strings.Join(placeholders, ", "))

	rows, err := s.db.Query(s.rebind(query), args...)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	byMonitor := make(map[string]map[string]DailyUptimeStat, len(ids))
	for rows.Next() {
		var monitorID string
		var stat DailyUptimeStat
		if err := rows.Scan(&monitorID, &stat.Date, &stat.Total, &stat.Up); err != nil {
			return nil, err
		}
		if stat.Total > 0 {
			stat.UptimePercent = (float64(stat.Up) / float64(stat.Total)) * 100.0
		}
		if byMonitor[monitorID] == nil {
			byMonitor[monitorID] = make(map[string]DailyUptimeStat)
		}
		byMonitor[monitorID][stat.Date] = stat
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	// Every requested id gets an entry, even one with no rollup rows in the window.
	out := make(map[string][]DailyUptimeStat, len(ids))
	for _, id := range ids {
		dayMap := byMonitor[id]
		filled := make([]DailyUptimeStat, days)
		for i := 0; i < days; i++ {
			d := now.AddDate(0, 0, -(days - 1 - i))
			dateStr := d.Format("2006-01-02")
			if stat, ok := dayMap[dateStr]; ok {
				filled[i] = stat
			} else {
				filled[i] = DailyUptimeStat{Date: dateStr, Total: 0, UptimePercent: -1}
			}
		}
		out[id] = filled
	}
	return out, nil
}

// RollupDailyUptime recomputes the daily uptime rollup for every monitor over the last
// `days` calendar days from raw checks, and upserts it. It uses the same aggregation as
// GetDailyUptimeStats, so a rollup row equals what a live query would return for that day.
// Idempotent: recomputing a day overwrites its row. A day with no checks produces no row,
// so the read path renders it as no-data (-1). The worker calls it with a small window to
// refresh recent days and, once at startup, with the retention window to backfill.
func (s *Store) RollupDailyUptime(days int) error {
	if days < 1 {
		return nil
	}

	var query string
	if s.IsPostgres() {
		query = `SELECT monitor_id, TO_CHAR(timestamp, 'YYYY-MM-DD') as day,
				COUNT(*), SUM(CASE WHEN status = 'up' THEN 1 ELSE 0 END)
			FROM monitor_checks
			WHERE timestamp >= NOW() - MAKE_INTERVAL(days => ?)
			GROUP BY monitor_id, day`
	} else {
		query = `SELECT monitor_id, DATE(timestamp) as day,
				COUNT(*), SUM(CASE WHEN status = 'up' THEN 1 ELSE 0 END)
			FROM monitor_checks
			WHERE timestamp >= datetime('now', '-' || ? || ' days')
			GROUP BY monitor_id, day`
	}

	rows, err := s.db.Query(s.rebind(query), days)
	if err != nil {
		return err
	}
	type rollup struct {
		monitorID, day string
		total, up      int
	}
	var rollups []rollup
	for rows.Next() {
		var r rollup
		if err := rows.Scan(&r.monitorID, &r.day, &r.total, &r.up); err != nil {
			_ = rows.Close()
			return err
		}
		rollups = append(rollups, r)
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		return err
	}
	// Close before writing: SQLite won't let us upsert while a read is still open.
	_ = rows.Close()

	if len(rollups) == 0 {
		return nil
	}

	// One transaction for all upserts: on the startup backfill this can be hundreds of rows,
	// and on SQLite a row-per-transaction would be that many fsyncs while holding the single
	// connection.
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	upsert := s.rebind(`INSERT INTO monitor_uptime_daily (monitor_id, day, total, up_count)
		VALUES (?, ?, ?, ?)
		ON CONFLICT(monitor_id, day) DO UPDATE SET total = excluded.total, up_count = excluded.up_count`)
	for _, r := range rollups {
		if _, err := tx.Exec(upsert, r.monitorID, r.day, r.total, r.up); err != nil {
			_ = tx.Rollback()
			return err
		}
	}
	return tx.Commit()
}

// PruneDailyRollups drops rollup rows older than the retention window. Historical rollups
// are otherwise frozen (the worker only recomputes recent days), so pruning raw checks
// never corrupts an older bar.
func (s *Store) PruneDailyRollups(days int) error {
	if days < 1 || days > 3650 {
		return fmt.Errorf("invalid retention days: must be between 1 and 3650")
	}
	cutoff := time.Now().UTC().AddDate(0, 0, -days).Format("2006-01-02")
	_, err := s.db.Exec(s.rebind("DELETE FROM monitor_uptime_daily WHERE day < ?"), cutoff)
	return err
}

// toNullInt64 converts an *int to sql.NullInt64 for nullable column storage.
func toNullInt64(v *int) sql.NullInt64 {
	if v == nil {
		return sql.NullInt64{}
	}
	return sql.NullInt64{Int64: int64(*v), Valid: true}
}

func (s *Store) GetLatencyStats(monitorID string, hours int) ([]LatencyPoint, error) {
	// SECURITY: Validate input
	if hours < 1 || hours > 8760 { // Max 1 year
		return nil, fmt.Errorf("invalid hours: must be between 1 and 8760")
	}

	var query string
	var groupBy string

	if s.IsPostgres() {
		if hours <= 1 {
			groupBy = "TO_CHAR(timestamp, 'YYYY-MM-DD HH24:MI:00')"
		} else if hours <= 168 {
			groupBy = "TO_CHAR(timestamp, 'YYYY-MM-DD HH24:00:00')"
		} else {
			groupBy = "TO_CHAR(timestamp, 'YYYY-MM-DD')"
		}
		// Use MAKE_INTERVAL for parameterized interval
		query = fmt.Sprintf(`
			SELECT
				%s as ts_group,
				CAST(AVG(latency) AS INTEGER) as avg_latency,
				MAX(CASE WHEN status != 'up' THEN 1 ELSE 0 END) as failed
			FROM monitor_checks
			WHERE monitor_id = $1
			AND timestamp > NOW() - MAKE_INTERVAL(hours => $2)
			GROUP BY ts_group
			ORDER BY ts_group ASC
		`, groupBy)
	} else {
		if hours <= 1 {
			groupBy = "strftime('%Y-%m-%d %H:%M:00', timestamp)"
		} else if hours <= 168 {
			groupBy = "strftime('%Y-%m-%d %H:00:00', timestamp)"
		} else {
			groupBy = "strftime('%Y-%m-%d', timestamp)"
		}
		query = fmt.Sprintf(`
			SELECT
				%s as ts_group,
				CAST(AVG(latency) AS INTEGER) as avg_latency,
				MAX(CASE WHEN status != 'up' THEN 1 ELSE 0 END) as failed
			FROM monitor_checks
			WHERE monitor_id = ?
			AND datetime(timestamp) > datetime('now', '-' || ? || ' hours')
			GROUP BY ts_group
			ORDER BY ts_group ASC
		`, groupBy)
	}

	var rows *sql.Rows
	var err error
	if s.IsPostgres() {
		rows, err = s.db.Query(query, monitorID, hours)
	} else {
		rows, err = s.db.Query(query, monitorID, hours)
	}
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var points []LatencyPoint
	for rows.Next() {
		var p LatencyPoint
		var tsStr string
		if err := rows.Scan(&tsStr, &p.Latency, &p.Failed); err != nil {
			return nil, err
		}

		// Parse timestamp string
		if len(tsStr) == 10 { // YYYY-MM-DD
			p.Timestamp, _ = time.Parse("2006-01-02", tsStr)
		} else {
			p.Timestamp, _ = time.Parse("2006-01-02 15:04:05", tsStr)
		}
		points = append(points, p)
	}
	return points, nil
}
